-- MySQL Script generated by MySQL Workbench
-- Thu Jan 10 11:05:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

drop table if exists noter;
drop table if exists promotion;
drop table if exists magasin;
drop table if exists categorie;
drop table if exists responsable;
drop table if exists avis;
drop table if exists client;
drop table if exists ville;
drop table type;


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ville` (
  `idville` INT NOT NULL AUTO_INCREMENT,
  `cp` VARCHAR(5) NOT NULL,
  `libelleType` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idville`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Type` (
  `idType` INT NOT NULL AUTO_INCREMENT,
  `libelleType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Responsable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Responsable` (
  `idResponsable` INT NOT NULL AUTO_INCREMENT,
  `nomResponsable` VARCHAR(45) NOT NULL,
  `prenomResponsable` VARCHAR(45) NOT NULL,
  `mailResponsable` VARCHAR(45) NOT NULL,
  `mdpRepsonsable` VARCHAR(45) NOT NULL,
  `telResponsable` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idResponsable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Categorie` (
  `idCategorie` INT NOT NULL AUTO_INCREMENT,
  `libelleCategorie` VARCHAR(45) NOT NULL,
  `idType` INT NOT NULL,
  PRIMARY KEY (`idCategorie`),
  CONSTRAINT `fk_Categorie_Type1`
    FOREIGN KEY (`idType`)
    REFERENCES `Type` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Magasin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Magasin` (
  `idMagasin` INT NOT NULL AUTO_INCREMENT,
  `nomMagasin` VARCHAR(45) NOT NULL,
  `adresseMagasin` VARCHAR(45) NOT NULL,
  `latMagasin` VARCHAR(45) NOT NULL,
  `longMagasin` VARCHAR(45) NOT NULL,
  `telMagasin` VARCHAR(10) NOT NULL,
  `mailMagasin` VARCHAR(45) NOT NULL,
  `siret` VARCHAR(45) NOT NULL,
  `photo1` VARCHAR(45) NULL,
  `photo2` VARCHAR(45) NULL,
  `idCategorie` INT NOT NULL,
  `idType` INT NOT NULL,
  `idville` INT NOT NULL,
  `idResponsable` INT NOT NULL,
  PRIMARY KEY (`idMagasin`),
  CONSTRAINT `fk_Magasin_Categorie1`
    FOREIGN KEY (`idCategorie`)
    REFERENCES `Categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Magasin_Type1`
    FOREIGN KEY (`idType`)
    REFERENCES `Type` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Magasin_Ville1`
    FOREIGN KEY (`idville`)
    REFERENCES `Ville` (`idville`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Magasin_Responsable1`
    FOREIGN KEY (`idResponsable`)
    REFERENCES `Responsable` (`idResponsable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Promotion` (
  `idPromotion` INT NOT NULL AUTO_INCREMENT,
  `promotionLibelle` VARCHAR(45) NOT NULL,
  `dateDebut` DATE NOT NULL,
  `dateFin` DATE NOT NULL,
  `photo1` VARCHAR(45) NULL,
  `photo2` VARCHAR(45) NULL,
  `photo3` VARCHAR(45) NULL,
  `codePromo` VARCHAR(45) NOT NULL,
  `active` TINYINT NULL,
  `idMagasin` INT NOT NULL,
  PRIMARY KEY (`idPromotion`),
  CONSTRAINT `fk_Promotion_Magasin1`
    FOREIGN KEY (`idMagasin`)
    REFERENCES `Magasin` (`idMagasin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nomClient` VARCHAR(45) NOT NULL,
  `prenomClient` VARCHAR(45) NOT NULL,
  `Ddn` DATE NOT NULL,
  `telClient` VARCHAR(10) NOT NULL,
  `mailclient` VARCHAR(45) NOT NULL,
  `mdpClient` VARCHAR(45) NOT NULL,
  `adresseClient` VARCHAR(75) NOT NULL,
  `idville` INT NOT NULL,
  PRIMARY KEY (`idClient`),
  CONSTRAINT `fk_Client_Ville1`
    FOREIGN KEY (`idville`)
    REFERENCES `Ville` (`idville`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Avis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Avis` (
  `codeAvis` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codeAvis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Noter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Noter` (
  `commentaire` VARCHAR(75) NULL,
  `note` VARCHAR(1) NULL,
  `codeAvis` INT NOT NULL,
  `idClient` INT NOT NULL,
  `idPromotion` INT NOT NULL,
  PRIMARY KEY (`codeAvis`, `idClient`, `idPromotion`),
  CONSTRAINT `fk_Noter_Avis`
    FOREIGN KEY (`codeAvis`)
    REFERENCES `Avis` (`codeAvis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Noter_Client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Noter_Promotion1`
    FOREIGN KEY (`idPromotion`)
    REFERENCES `Promotion` (`idPromotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
